name: CI

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request: ~

jobs:
  cs-fix:
    name: Run code style check
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        php:
          - '8.0'
    steps:
      -   uses: actions/checkout@v3

      -   name: Setup PHP Action
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            coverage: none
            extensions: 'pdo_sqlite, gd'
            tools: cs2pr

      -   uses: "ramsey/composer-install@v2"
          with:
            dependency-versions: "highest"

      -   name: Run code style check
          run: composer run-script check-cs -- --format=checkstyle | cs2pr

  tests:
    name: Tests
    runs-on: "ubuntu-20.04"
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.4'
          - '8.1'
          - '8.0'
          - '7.4'

    steps:
      -   uses: actions/checkout@v2

      -   name: Setup PHP Action
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            coverage: none
            extensions: ${{ matrix.extensions }}
            tools: cs2pr

      -   uses: "ramsey/composer-install@v2"
          with:
            dependency-versions: "highest"

      -   name: Setup problem matchers for PHPUnit
          run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      -   name: Run PHPStan analysis
          run: composer phpstan

      -   name: Run test
          run: composer test

      -   name: Run integration tests
          run: composer test-integration